on: pull_request
name: SonarQube Check
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}
        projectBaseDir: "."
        # args: >
        #   -Dsonar.organization=my-organization
        #   -Dsonar.projectKey=my-projectkey
        #   -Dsonar.python.coverage.reportPaths=coverage.xml
        #   -Dsonar.sources=lib/
        #   -Dsonar.test.exclusions=tests/**
        #   -Dsonar.tests=tests/
        #   -Dsonar.verbose=true
        projectKey: "petclinic"
        projectName: "petclinic"
